services:
  expenses-database:
    image: postgres:16
    container_name: expenses-database
    environment:
      - POSTGRES_DB=expenses
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  expenses-backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: expenses-backend
    ports:
      - "7000:7000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@expenses-database:5432/expenses
    depends_on:
      - expenses-database
